/**
 * Static quote defaults (drywall app BASE_DEFAULTS). Org settings UI is out of scope for C.1.
 */
export const DRYWALL_QUOTE_BASE_DEFAULTS = {
  overheadPercentage: 10,
  profitPercentage: 30,
  salesTaxRate: 7.25,
  quoteIncludes: 'labor_and_material' as const,
  wastePercentage: 0,
  materialRate: 0.66,
  hangerRate: 0.27,
  finisherRate: 0.27,
  prepCleanRate: 0.03,
  suspendedGridWastePercentage: 0,
  carpenterRate: 2.0,
  suspendedGridPricing: {
    shiny90Rate: 0,
    mainsRate: 0,
    tees4ftRate: 0,
    wireRate: 0,
    lagsRate: 0,
  },
  rcChannelWastePercentage: 0,
  rcChannelRate: 0,
  rcChannelLaborRate: 0,
  insulationWastePercentage: 0,
  insulationCeilingLaborRate: 0,
  insulationWallLaborRate: 0,
  insulationPricing: {
    r13BattsUnfacedRate: 0,
    r13BattsPaperFacedRate: 0,
    r19BattsUnfacedRate: 0,
    r19BattsPaperFacedRate: 0,
    r21BattsUnfacedRate: 0,
    r21BattsPaperFacedRate: 0,
    r30BattsUnfacedRate: 0,
    r30BattsPaperFacedRate: 0,
    r38BattsUnfacedRate: 0,
    r38BattsPaperFacedRate: 0,
    soundAttenuationBattsUnfacedRate: 0,
    soundAttenuationBattsPaperFacedRate: 0,
    rigidInsulation1Rate: 0,
    rigidInsulation2Rate: 0,
  },
  acousticCeilingWastePercentage: 0,
  acousticCeilingTileRate: 0,
  acousticCeilingLaborRate: 0,
  acousticCeilingGridPricing: {
    wallAngleRate: 0,
    mainsRate: 0,
    tees4ftRate: 0,
    tees2ftRate: 0,
    wireRate: 0,
    lagsRate: 0,
  },
  metalStudWastePercentage: 0,
  metalStudLaborRate: 0,
  metalStudStudRates: {
    '2.5_18': 0,
    '2.5_20': 0,
    '2.5_25': 0,
    '3.625_18': 0,
    '3.625_20': 0,
    '3.625_25': 0,
    '6_18': 0,
    '6_20': 0,
    '6_25': 0,
  },
  metalStudTrackRates: {
    '2.5_18': 0,
    '2.5_20': 0,
    '2.5_25': 0,
    '3.625_18': 0,
    '3.625_20': 0,
    '3.625_25': 0,
    '6_18': 0,
    '6_20': 0,
    '6_25': 0,
  },
  frpWastePercentage: 0,
  frpSheetRate: 0,
  frpAdhesiveBucketRate: 0,
  frpDivisionStickRate: 0,
  frpIcStickRate: 0,
  frpOcStickRate: 0,
  frpJMoldStickRate: 0,
  drywallScope: 'hang_and_finish' as const,
  hangLayers: '1',
  finishLayers: '1',
}

export type DrywallQuoteDefaults = typeof DRYWALL_QUOTE_BASE_DEFAULTS
